#!/usr/bin/env python3
"""
OMR Detector — Arabic Answer Sheet (100 questions, corner-anchor design)

Sheet layout (RTL, generated by generate_answer_page.py):
  • 4 solid black corner anchors (12 mm × 12 mm, inset 5 mm from each corner)
  • 2 QR codes (top-left area in RTL layout): student code + exam code
  • 100 questions in 4 columns, 25 rows per column, displayed RTL:
      rightmost column = Q 1–25
      next             = Q26–50
      next             = Q51–75
      leftmost column  = Q76–100
  • Each row's bubbles ordered RTL (rightmost = أ / A, then ب/B, ج/C, د/D)

Debug images saved to:  detected-<stem>/
  00_original.jpg
  01_doc_corners.jpg       — detected document boundary
  02_warped.jpg            — perspective-corrected A4
  03_anchor_search.jpg     — corner search regions
  04_anchors.jpg           — verified anchor positions
  05_qr_regions.jpg        — QR crop used for decoding
  06_answer_area.jpg       — answer grid bounding box
  07_circles_raw.jpg       — all HoughCircles (green=filled / orange=empty)
  08_circles_classified.jpg— circles mapped to col-group × row with choice label
  09_answered.jpg          — final annotated answer sheet

Usage:
  python omr_detector.py ar-student-answer.jpeg
  python omr_detector.py ar-student-answer.jpeg --questions 100
"""

import cv2
import numpy as np
import json
import sys
import pathlib
import argparse
from collections import defaultdict

# ── CONFIG ────────────────────────────────────────────────────────────────────

CFG = {
    # Output size for perspective-warped A4 (750 × 1060 → 1px ≈ 0.28 mm)
    "warp_w": 750,
    "warp_h": 1060,

    # Anchor squares: 12 mm side, inset 5 mm from each corner on A4 (210 × 297 mm)
    # Expected center positions in warped image (mm→px = mm/210*750 or mm/297*1060)
    # anchor center = inset(5mm) + half_side(6mm) = 11 mm from each edge
    "anchor_cx_left":   int(11 / 210 * 750),   # ≈ 39 px
    "anchor_cx_right":  int((210 - 11) / 210 * 750),  # ≈ 711 px
    "anchor_cy_top":    int(11 / 297 * 1060),   # ≈ 39 px
    "anchor_cy_bottom": int((297 - 11) / 297 * 1060), # ≈ 1021 px
    "anchor_search_r":  50,   # px search radius around expected anchor center
    "anchor_min_area":  600,  # px² minimum dark blob to consider as anchor
    "anchor_max_area":  5000, # px² maximum

    # Answer grid bounds — computed relative to the detected anchor square centres.
    # This keeps the crop consistent regardless of photo zoom / perspective.
    # Fractions of (anchor_bottom - anchor_top) added to anchor_top, etc.
    # Layout: header takes ~27 % of the inter-anchor span; footer leaves ~3 %.
    "grid_anchor_top":   0.205,   # start this far below the top anchor row
    "grid_anchor_bot":   0.975,  # end this far below the top anchor row
    "grid_anchor_left":  0.06,   # inset this far right of the left anchor col
    "grid_anchor_right": 0.06,   # inset this far left of the right anchor col

    # Fallback fractions (used only when anchor detection fails)
    "grid_x0": 0.10,
    "grid_x1": 0.90,
    "grid_y0": 0.247,
    "grid_y1": 0.94,

    # QR code region (RTL: QR section is on LEFT side of the header row)
    # Wider crop to give the decoder more pixels to work with
    "qr_x0": 0.08,
    "qr_x1": 0.42,
    "qr_y0": 0.08,
    "qr_y1": 0.25,

    # HoughCircles (parameters for bubble radius ≈ 8-9 px in warped image)
    # Actual bubble: 17px CSS diameter → ~8px radius in 750px-wide warped image
    "hough_dp":       1.2,
    "hough_min_dist": 17,    # ≥ bubble pitch (~20px); prevents double-detecting same bubble
    "hough_param1":   50,
    "hough_param2":   18,    # stricter accumulator: fewer false arcs
    "hough_min_r":    7,     # exclude tiny letter-counter detections (r=5-6)
    "hough_max_r":    13,    # 24px CSS bubble → ~11.4px warped radius; allow up to 13

    # NMS: merge/drop circles whose centres are closer than this (px)
    "nms_dist": 14,

    # Fill classification (Shading Corrected)
    "fill_norm_thr":  180,  # normalized pixel value < this is considered "dark" (out of 255)
                            # ~180 means 70% of the local background brightness
    "fill_ratio_thr": 0.40, # tuned for lighter/thinner printed font (but high enough for old thick fonts)

    # Layout
    "n_col_groups":     4,
    "rows_per_group":   25,
    "n_questions":      100,
}

# RTL choice mapping: rank from rightmost (0) → answer letter
RANK_TO_CHOICE = {0: "A", 1: "B", 2: "C", 3: "D"}

# ── DEBUG HELPERS ─────────────────────────────────────────────────────────────

def _dbg(img: np.ndarray, name: str, debug_dir: pathlib.Path):
    debug_dir.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(debug_dir / name), img)

def _to_bgr(img: np.ndarray) -> np.ndarray:
    return cv2.cvtColor(img, cv2.COLOR_GRAY2BGR) if len(img.shape) == 2 else img.copy()

# ── STEP 1: LOAD & PREPROCESS ─────────────────────────────────────────────────

def load_image(path: str):
    img = cv2.imread(path)
    if img is None:
        raise FileNotFoundError(f"Cannot read: {path}")
    return img

def preprocess(img: np.ndarray) -> np.ndarray:
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    return clahe.apply(gray)

# ── STEP 2: DOCUMENT DETECTION + WARP ────────────────────────────────────────

def _order_points(pts: np.ndarray) -> np.ndarray:
    """Return [TL, TR, BR, BL] order."""
    rect = np.zeros((4, 2), dtype=np.float32)
    s = pts.sum(axis=1)
    rect[0] = pts[np.argmin(s)]  # TL: smallest x+y
    rect[2] = pts[np.argmax(s)]  # BR: largest x+y
    d = np.diff(pts, axis=1)
    rect[1] = pts[np.argmin(d)]  # TR: smallest x-y
    rect[3] = pts[np.argmax(d)]  # BL: largest x-y
    return rect

def find_document_corners(gray: np.ndarray) -> np.ndarray | None:
    """Canny + largest quadrilateral contour that covers at least 35% of image."""
    H, W = gray.shape
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    for lo, hi in [(50, 150), (30, 100), (10, 60)]:
        edges = cv2.Canny(blur, lo, hi)
        k = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
        edges = cv2.dilate(edges, k, iterations=1)
        cnts, _ = cv2.findContours(edges, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
        cnts = sorted(cnts, key=cv2.contourArea, reverse=True)
        for c in cnts[:10]:
            # Must cover at least 35% of image to be considered a document boundary
            if cv2.contourArea(c) < 0.35 * H * W:
                continue
            peri = cv2.arcLength(c, True)
            approx = cv2.approxPolyDP(c, 0.02 * peri, True)
            if len(approx) == 4:
                return approx.reshape(4, 2).astype(np.float32)
    return None

def warp_document(img: np.ndarray, corners: np.ndarray,
                  out_w: int, out_h: int) -> np.ndarray:
    rect = _order_points(corners)
    dst = np.float32([[0, 0], [out_w - 1, 0],
                      [out_w - 1, out_h - 1], [0, out_h - 1]])
    M = cv2.getPerspectiveTransform(rect, dst)
    return cv2.warpPerspective(img, M, (out_w, out_h),
                               flags=cv2.INTER_CUBIC,
                               borderMode=cv2.BORDER_REPLICATE)

def find_anchors_in_original(img: np.ndarray) -> dict | None:
    """
    Search globally for the 4 black anchor squares of the OMR template.
    Returns {TL/TR/BR/BL: (cx, cy)} in original image coords, or None if failed.
    """
    import itertools
    H, W = img.shape[:2]
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Adaptive threshold handles varying brightness/shadows beautifully
    bw = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 51, 15)
    cnts, _ = cv2.findContours(bw, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    
    candidates = []
    # An anchor is typically ~12mm. In pixels, side should be >1.2% and <15% of min(W,H).
    min_side = min(W, H) * 0.012
    max_side = min(W, H) * 0.15
    min_area = min_side ** 2
    max_area = max_side ** 2
    
    for c in cnts:
        area = cv2.contourArea(c)
        if area < min_area or area > max_area:
            continue
        x, y, w, h = cv2.boundingRect(c)
        ratio = min(w, h) / max(w, h) if max(w, h) > 0 else 0
        if ratio < 0.65:
            continue
        hull = cv2.convexHull(c)
        solidity = area / (cv2.contourArea(hull) + 1e-6)
        if solidity < 0.70:
            continue
            
        M = cv2.moments(c)
        if M["m00"] == 0: continue
        cx = int(M["m10"] / M["m00"])
        cy = int(M["m01"] / M["m00"])
        candidates.append((cx, cy, area))
        
    if len(candidates) < 4:
        return None
        
    # Sort by area descending, take top 12 largest squares
    candidates.sort(key=lambda x: x[2], reverse=True)
    top_cands = candidates[:12]
    
    best_quad = None
    max_quad_area = 0
    
    for quad in itertools.combinations(top_cands, 4):
        pts = np.float32([[p[0], p[1]] for p in quad])
        ordered = _order_points(pts)
        quad_area = cv2.contourArea(ordered)
        
        if quad_area > max_quad_area:
            # Check sanity: must be roughly rectangular
            tl, tr, br, bl = ordered
            w_top = np.linalg.norm(tr - tl)
            w_bot = np.linalg.norm(br - bl)
            h_left = np.linalg.norm(bl - tl)
            h_right = np.linalg.norm(br - tr)
            
            if min(w_top, w_bot) / max(w_top, w_bot) > 0.7 and \
               min(h_left, h_right) / max(h_left, h_right) > 0.7:
                max_quad_area = quad_area
                best_quad = ordered
                
    # Quad must cover at least 5% of the image (prevents picking tiny random clusters)
    if best_quad is not None and max_quad_area > (W * H * 0.05):
        return {
            "TL": tuple(best_quad[0].astype(int)),
            "TR": tuple(best_quad[1].astype(int)),
            "BR": tuple(best_quad[2].astype(int)),
            "BL": tuple(best_quad[3].astype(int)),
        }
    return None


def align(img: np.ndarray, debug_dir: pathlib.Path) -> tuple[np.ndarray, str]:
    """Return (warped_BGR, method_str).

    Priority:
      1. canny-contour — Canny edge + largest quad (works when dark border is present)
      2. anchor-based  — find anchor squares in original image → fallback for flat paper
      3. full-image    — last resort; crops 10px from each edge
    """
    W, H = CFG["warp_w"], CFG["warp_h"]
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    Ih, Iw = gray.shape

    method  = None
    rect    = None   # [TL, TR, BR, BL] source corners in original image
    warped  = None

    # ── Method 1: anchor-based (most robust, uses fiducials) ────────────
    orig_anchors = find_anchors_in_original(img)
    if orig_anchors:
        method = "anchor-based"
        dst_pts = np.float32([
            [CFG["anchor_cx_left"],  CFG["anchor_cy_top"]],     # TL
            [CFG["anchor_cx_right"], CFG["anchor_cy_top"]],     # TR
            [CFG["anchor_cx_right"], CFG["anchor_cy_bottom"]],  # BR
            [CFG["anchor_cx_left"],  CFG["anchor_cy_bottom"]],  # BL
        ])
        src_pts = np.float32([orig_anchors["TL"], orig_anchors["TR"],
                               orig_anchors["BR"], orig_anchors["BL"]])
        M = cv2.getPerspectiveTransform(src_pts, dst_pts)
        warped = cv2.warpPerspective(img, M, (W, H),
                                     flags=cv2.INTER_CUBIC,
                                     borderMode=cv2.BORDER_REPLICATE)
        rect = src_pts

    # ── Method 2: Canny contour (fallback if anchors aren't visible) ─────────
    if warped is None:
        corners = find_document_corners(gray)
        if corners is not None:
            method = "canny-contour"
            rect   = _order_points(corners)
            warped = warp_document(img, rect, W, H)

    # ── Method 3: full-image fallback ─────────────────────────────────────────
    if warped is None:
        print("[WARN] Anchor and Canny both failed — using full-image bounds")
        method = "full-image"
        rect = _order_points(np.float32([
            [10, 10], [Iw - 10, 10],
            [Iw - 10, Ih - 10], [10, Ih - 10]
        ]))
        warped = warp_document(img, rect, W, H)

    # Debug: draw detected document outline on original
    vis = img.copy()
    tl, tr, br, bl = [tuple(p.astype(int)) for p in rect]
    cv2.polylines(vis, [rect.astype(np.int32)], True, (0, 255, 80), 3)
    for pt, col, lbl in zip([tl, tr, br, bl],
                             [(0, 0, 255), (0, 200, 0), (0, 165, 255), (255, 100, 0)],
                             ["TL", "TR", "BR", "BL"]):
        cv2.circle(vis, pt, 12, col, -1)
        cv2.putText(vis, lbl, (pt[0] + 8, pt[1] - 8),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, col, 2)
    cv2.putText(vis, method, (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (0, 200, 255), 2)
    _dbg(vis, "01_doc_corners.jpg", debug_dir)

    _dbg(warped, "02_warped.jpg", debug_dir)
    print(f"  [align] method={method}  out={W}x{H}")
    return warped, method

# ── STEP 3: ANCHOR VERIFICATION ──────────────────────────────────────────────

def _find_anchor_in_region(gray_patch: np.ndarray) -> tuple[int, int] | None:
    """Find the centroid of the largest dark blob in a search patch."""
    _, bw = cv2.threshold(gray_patch, 60, 255, cv2.THRESH_BINARY_INV)
    cnts, _ = cv2.findContours(bw, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not cnts:
        return None
    best = None
    for c in cnts:
        area = cv2.contourArea(c)
        if area < CFG["anchor_min_area"] or area > CFG["anchor_max_area"]:
            continue
        x, y, w, h = cv2.boundingRect(c)
        ratio = min(w, h) / max(w, h) if max(w, h) > 0 else 0
        if ratio < 0.55:  # reject non-square shapes
            continue
        if best is None or area > cv2.contourArea(best):
            best = c
    if best is None:
        return None
    M = cv2.moments(best)
    if M["m00"] == 0:
        return None
    cx = int(M["m10"] / M["m00"])
    cy = int(M["m01"] / M["m00"])
    return (cx, cy)

def verify_anchors(warped: np.ndarray, debug_dir: pathlib.Path) -> dict:
    """
    Search for the 4 anchor squares at their expected positions.
    Returns dict with keys TL/TR/BR/BL and (cx, cy) values in warped coords.
    Falls back to expected positions if detection fails.
    """
    gray = cv2.cvtColor(warped, cv2.COLOR_BGR2GRAY)
    r = CFG["anchor_search_r"]

    expected = {
        "TL": (CFG["anchor_cx_left"],  CFG["anchor_cy_top"]),
        "TR": (CFG["anchor_cx_right"], CFG["anchor_cy_top"]),
        "BR": (CFG["anchor_cx_right"], CFG["anchor_cy_bottom"]),
        "BL": (CFG["anchor_cx_left"],  CFG["anchor_cy_bottom"]),
    }

    vis_search = _to_bgr(gray)
    anchors = {}
    for name, (ex, ey) in expected.items():
        # Clamp search region
        x0 = max(0, ex - r); x1 = min(warped.shape[1], ex + r)
        y0 = max(0, ey - r); y1 = min(warped.shape[0], ey + r)
        patch = gray[y0:y1, x0:x1]

        # Draw search region
        cv2.rectangle(vis_search, (x0, y0), (x1, y1), (200, 200, 0), 2)

        local = _find_anchor_in_region(patch)
        if local:
            cx = x0 + local[0]
            cy = y0 + local[1]
            anchors[name] = (cx, cy)
            cv2.circle(vis_search, (cx, cy), 8, (0, 255, 0), -1)
            cv2.putText(vis_search, name, (cx + 5, cy - 5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)
        else:
            anchors[name] = expected[name]  # fallback
            cv2.circle(vis_search, expected[name], 8, (0, 0, 255), -1)
            cv2.putText(vis_search, f"{name}?", (expected[name][0] + 5, expected[name][1] - 5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1)

    _dbg(vis_search, "03_anchor_search.jpg", debug_dir)

    # Draw confirmed anchors on warped
    vis_anch = warped.copy()
    for name, (cx, cy) in anchors.items():
        cv2.circle(vis_anch, (cx, cy), 20, (0, 255, 255), 3)
        cv2.putText(vis_anch, name, (cx - 30, cy - 25),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 255), 2)
    _dbg(vis_anch, "04_anchors.jpg", debug_dir)

    print(f"  [anchors] " + " ".join(f"{k}={v}" for k, v in anchors.items()))
    return anchors

# ── STEP 4: QR CODE DECODING ──────────────────────────────────────────────────

def decode_qr_codes(warped: np.ndarray, debug_dir: pathlib.Path) -> dict:
    """
    Decode both QR codes (student + exam) from the top-left area.

    Decode chain (first success wins per sub-region):
      1. pyzbar  — most robust, handles blur/JPEG/moiré well
      2. OpenCV QRCodeDetector — fast fallback
      3. OCR on printed text fields — last resort

    Classify by value prefix: STU-* → student,  EXAM-* → exam
    """
    H, W = warped.shape[:2]
    x0 = int(W * CFG["qr_x0"]); x1 = int(W * CFG["qr_x1"])
    y0 = int(W * CFG["qr_y0"]); y1 = int(H * CFG["qr_y1"])
    # Use H for y coords
    y0 = int(H * CFG["qr_y0"]); y1 = int(H * CFG["qr_y1"])
    region = warped[y0:y1, x0:x1]
    _dbg(region, "05_qr_regions.jpg", debug_dir)

    rh, rw = region.shape[:2]

    # ── Try pyzbar ─────────────────────────────────────────────────────────────
    try:
        from pyzbar import pyzbar as pzb

        def _pyzbar_decode(img_bgr: np.ndarray) -> list[str]:
            gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
            found = []
            for scale in [2, 3, 1]:
                g = cv2.resize(gray, None, fx=scale, fy=scale,
                               interpolation=cv2.INTER_CUBIC) if scale > 1 else gray
                # Three preprocessing variants
                _, bw1 = cv2.threshold(g, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
                clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(4, 4))
                _, bw2 = cv2.threshold(clahe.apply(g), 0, 255,
                                       cv2.THRESH_BINARY + cv2.THRESH_OTSU)
                bw3 = cv2.adaptiveThreshold(g, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                            cv2.THRESH_BINARY, 15, 4)
                for bw in [bw1, bw2, bw3]:
                    for obj in pzb.decode(bw):
                        val = obj.data.decode("utf-8", errors="ignore").strip()
                        if val and val not in found:
                            found.append(val)
                if found:
                    return found
            return found

        sub_regions = [
            region,
            region[:, : rw // 2],     # left half  (exam QR in RTL)
            region[:, rw // 2 :],     # right half (student QR in RTL)
        ]
        all_codes: list[str] = []
        for sub in sub_regions:
            for code in _pyzbar_decode(sub):
                if code not in all_codes:
                    all_codes.append(code)
            if len(all_codes) >= 2:
                break

        pyzbar_ok = bool(all_codes)
    except Exception as e:
        print(f"  [qr] pyzbar unavailable: {e}")
        all_codes = []
        pyzbar_ok = False

    # ── OpenCV fallback ────────────────────────────────────────────────────────
    if not all_codes:
        detector = cv2.QRCodeDetector()
        gray_reg = cv2.cvtColor(region, cv2.COLOR_BGR2GRAY)
        for scale in [3, 2, 1]:
            g = cv2.resize(gray_reg, None, fx=scale, fy=scale,
                           interpolation=cv2.INTER_CUBIC) if scale > 1 else gray_reg
            _, bw = cv2.threshold(g, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
            val, *_ = detector.detectAndDecode(bw)
            if val and val not in all_codes:
                all_codes.append(val)

    # ── Classify by prefix ─────────────────────────────────────────────────────
    student_code = "UNKNOWN"
    exam_code    = "UNKNOWN"
    for code in all_codes:
        up = code.upper()
        if up.startswith("STU") and student_code == "UNKNOWN":
            student_code = code
        elif exam_code == "UNKNOWN":
            exam_code = code

    method = "pyzbar" if pyzbar_ok else ("opencv" if all_codes else "none")
    print(f"  [qr] method={method}  decoded={all_codes}")
    print(f"       student={student_code}  exam={exam_code}")
    return {
        "student_code": student_code,
        "exam_code":    exam_code,
        "qr_raw":       all_codes,
        "qr_method":    method,
    }

# ── STEP 5: CIRCLE DETECTION ──────────────────────────────────────────────────

def _nms_circles(circles: list[dict]) -> list[dict]:
    """
    Non-Maximum Suppression for circles.
    If two detected circles are closer than nms_dist px, keep the one
    with the larger radius (more likely to be the true bubble border).
    Removes letter-counter detections (small, offset) and merged-bubble
    arcs (oversized, off-centre) that slip through HoughCircles.
    """
    if not circles:
        return circles
    nms_d = CFG["nms_dist"]
    # Sort descending by radius so the "real" bubble edge wins over inner detections
    sorted_c = sorted(circles, key=lambda c: c["r"], reverse=True)
    kept: list[dict] = []
    for cand in sorted_c:
        suppress = False
        for k in kept:
            dist = np.hypot(cand["cx"] - k["cx"], cand["cy"] - k["cy"])
            if dist < nms_d:
                suppress = True
                break
        if not suppress:
            kept.append(cand)
    return kept


def detect_circles(gray: np.ndarray) -> list[dict]:
    """HoughCircles + fill-ratio classification."""
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    raw = cv2.HoughCircles(
        blurred,
        cv2.HOUGH_GRADIENT,
        dp=CFG["hough_dp"],
        minDist=CFG["hough_min_dist"],
        param1=CFG["hough_param1"],
        param2=CFG["hough_param2"],
        minRadius=CFG["hough_min_r"],
        maxRadius=CFG["hough_max_r"],
    )
    results = []
    if raw is None:
        return results
    H, W = gray.shape

    # ── SHADING CORRECTION ──
    # Estimate background illumination using a large median blur (71x71)
    # This acts as a robust local background map, removing circles/pen marks.
    bg = cv2.medianBlur(gray, 71)
    bg = np.maximum(bg, 1)  # avoid division by zero
    
    # Normalize: pixel = (gray / bg) * 255
    # If a pixel matches background, norm ≈ 255. If it's a dark pen mark, norm < 200.
    norm = np.clip((gray.astype(np.float32) / bg.astype(np.float32)) * 255, 0, 255).astype(np.uint8)

    # Pre-compute dark binary using shading-corrected image
    dark_binary = (norm < CFG["fill_norm_thr"]).astype(np.uint8)

    for (cx, cy, r) in np.uint16(np.around(raw[0])):
        cx, cy, r = int(cx), int(cy), int(r)
        if cx - r < 0 or cy - r < 0 or cx + r >= W or cy + r >= H:
            continue
        mask = np.zeros((H, W), np.uint8)
        cv2.circle(mask, (cx, cy), max(r - 1, 2), 255, -1)
        nz = np.count_nonzero(mask)
        if nz == 0:
            continue
        dark = int(np.sum(dark_binary[mask > 0]))
        fill = dark / nz
        results.append({
            "cx": cx, "cy": cy, "r": r,
            "fill": round(fill, 3),
            "filled": fill > CFG["fill_ratio_thr"],
        })
    return _nms_circles(results)

def detect_answer_circles(warped: np.ndarray,
                           debug_dir: pathlib.Path,
                           anchors: dict | None = None) -> tuple[list[dict], np.ndarray]:
    """Detect circles inside the answer grid region."""
    H, W = warped.shape[:2]

    if anchors and len(anchors) == 4:
        # Compute grid bounds relative to the four anchor centres — robust
        # across different photo zooms and perspectives.
        ay_top   = min(anchors["TL"][1], anchors["TR"][1])
        ay_bot   = max(anchors["BL"][1], anchors["BR"][1])
        ax_left  = min(anchors["TL"][0], anchors["BL"][0])
        ax_right = max(anchors["TR"][0], anchors["BR"][0])
        anchor_h = ay_bot - ay_top
        anchor_w = ax_right - ax_left
        y0 = int(ay_top  + anchor_h * CFG["grid_anchor_top"])
        y1 = int(ay_top  + anchor_h * CFG["grid_anchor_bot"])
        x0 = int(ax_left + anchor_w * CFG["grid_anchor_left"])
        x1 = int(ax_right - anchor_w * CFG["grid_anchor_right"])
        print(f"  [grid] anchor-relative  y0={y0} y1={y1} x0={x0} x1={x1}")
    else:
        # Fallback: fixed fractions of the warped image
        x0 = int(W * CFG["grid_x0"]); x1 = int(W * CFG["grid_x1"])
        y0 = int(H * CFG["grid_y0"]); y1 = int(H * CFG["grid_y1"])
        print(f"  [grid] fixed-fraction   y0={y0} y1={y1} x0={x0} x1={x1}")

    # Debug: show answer area bounding box
    vis_area = warped.copy()
    cv2.rectangle(vis_area, (x0, y0), (x1, y1), (0, 100, 255), 2)
    cv2.putText(vis_area, "answer grid", (x0 + 4, y0 - 6),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 100, 255), 1)
    _dbg(vis_area, "06_answer_area.jpg", debug_dir)

    region = warped[y0:y1, x0:x1]
    gray_region = cv2.cvtColor(region, cv2.COLOR_BGR2GRAY)

    circles_local = detect_circles(gray_region)
    # Shift coords back to warped-image space
    circles = [dict(c, cx=c["cx"] + x0, cy=c["cy"] + y0)
               for c in circles_local]

    # Debug: draw all circles on warped image
    vis_raw = warped.copy()
    for c in circles:
        color = (0, 200, 0) if c["filled"] else (0, 140, 255)
        cv2.circle(vis_raw, (c["cx"], c["cy"]), c["r"], color, 2)
        cv2.putText(vis_raw, f"{c['fill']:.2f}",
                    (c["cx"] - 14, c["cy"] - c["r"] - 2),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.22, color, 1)
    _dbg(vis_raw, "07_circles_raw.jpg", debug_dir)

    print(f"  [circles] detected={len(circles)} "
          f"filled={sum(1 for c in circles if c['filled'])}")
    return circles, region

# ── STEP 6: CLUSTERING ────────────────────────────────────────────────────────

def _kmeans_1d(values: list[float], k: int) -> tuple[list[int], list[float]]:
    """
    K-means on 1D values. Returns (labels_sorted_asc, centers_sorted_asc).
    'labels_sorted_asc[i]' = cluster index in ascending-center order for values[i].
    """
    if len(values) < k:
        k = max(1, len(values))
    arr = np.array(values, dtype=np.float32).reshape(-1, 1)
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 200, 0.5)
    best_labels, best_centers, best_compact = None, None, float("inf")
    for _ in range(6):
        compact, labels, centers = cv2.kmeans(
            arr, k, None, criteria, 10, cv2.KMEANS_PP_CENTERS
        )
        if compact < best_compact:
            best_compact = compact
            best_labels = labels.flatten().tolist()
            best_centers = centers.flatten().tolist()

    # Build re-index: old_label → new_label (sorted ascending by center value)
    sorted_pairs = sorted(enumerate(best_centers), key=lambda x: x[1])
    old_to_new = {old: new for new, (old, _) in enumerate(sorted_pairs)}
    new_labels = [old_to_new[l] for l in best_labels]
    new_centers = [c for _, c in sorted_pairs]
    return new_labels, new_centers

def cluster_circles(circles: list[dict], n_col_groups: int,
                    rows_per_group: int) -> dict:
    """
    Group circles into (col_group_idx, row_idx) cells.

    col_group_idx 0 = leftmost column group (Q76-100)
    col_group_idx 3 = rightmost column group (Q1-25)

    row_idx 0 = topmost row (first question in group)

    Returns nested dict: result[col_group_idx][row_idx] = list of circle dicts
    """
    if not circles:
        return {}

    # ── Cluster by X into column groups ──────────────────────────────────────
    xs = [c["cx"] for c in circles]
    col_labels, col_centers = _kmeans_1d(xs, n_col_groups)

    # Assign circles to column groups
    col_groups: dict[int, list[dict]] = defaultdict(list)
    for circle, col_label in zip(circles, col_labels):
        col_groups[col_label].append(circle)

    # ── Within each column group, cluster by Y into rows ─────────────────────
    result: dict[int, dict[int, list[dict]]] = {}
    for col_idx in range(n_col_groups):
        group_circles = col_groups.get(col_idx, [])
        if not group_circles:
            result[col_idx] = {}
            continue

        ys = [c["cy"] for c in group_circles]
        # Force the expected row count; k-means handles it as long as there are
        # enough circles (which there always are for a completed answer sheet).
        k_rows = min(rows_per_group, len(group_circles))
        k_rows = max(1, k_rows)
        row_labels, _ = _kmeans_1d(ys, k_rows)

        rows: dict[int, list[dict]] = defaultdict(list)
        for circle, row_label in zip(group_circles, row_labels):
            rows[row_label].append(circle)
        result[col_idx] = dict(rows)

    return result

# ── STEP 7: EXTRACT ANSWERS ───────────────────────────────────────────────────

def extract_answers(cluster_grid: dict, n_col_groups: int,
                    rows_per_group: int) -> dict:
    """
    For each question: find the filled bubble and map to choice letter.

    Column group → question range (RTL layout):
      col_group 0 (leftmost)  → Q 76-100
      col_group 1             → Q 51-75
      col_group 2             → Q 26-50
      col_group 3 (rightmost) → Q  1-25

    Within each group, row 0 (topmost) = first question.

    Within each row, circles sorted by X descending → rank 0 (rightmost) = A (أ).

    Fill detection strategy — two-tier:
      Tier 1 (absolute):  fill > FILL_ABS_THR   → definitely filled
      Tier 2 (relative):  fill > row_mean + FILL_REL_MARGIN  → filled relative to row
      If tier-1 disagrees with tier-2, prefer tier-1 unless all fills are below ABS_THR
      (handles both real pen marks AND empty sheets with letter noise).
    """
    FILL_ABS_THR    = CFG["fill_ratio_thr"]   # 0.35 – absolute threshold
    FILL_REL_MARGIN = 0.06   # must exceed row mean by this margin to be relatively filled
    FILL_MIN_SIGNAL = 0.28   # minimum fill to even consider as a candidate
    FILL_DOMINANT_R = 1.35   # Tier-3: max fill must be ≥ this × 2nd-highest fill

    answers = {}
    details = {}

    for col_idx in range(n_col_groups):
        base_q = (n_col_groups - 1 - col_idx) * rows_per_group + 1
        rows = cluster_grid.get(col_idx, {})

        for row_idx in range(rows_per_group):
            q_num = base_q + row_idx
            q_str = str(q_num)
            row_circles = rows.get(row_idx, [])

            if not row_circles:
                answers[q_str] = None
                details[q_str] = {"choice": None, "note": "no_circles"}
                continue

            row_sorted = sorted(row_circles, key=lambda c: c["cx"], reverse=True)
            fills      = [c["fill"] for c in row_sorted]
            n_choices  = len(row_sorted)
            row_mean   = float(np.mean(fills))
            row_max    = max(fills)

            # ── Tier 1: absolute threshold ────────────────────────────────────
            abs_filled  = [(r, c) for r, c in enumerate(row_sorted)
                           if c["fill"] >= FILL_ABS_THR]

            # ── Tier 2: relative — significantly above row average ─────────────
            rel_filled  = [(r, c) for r, c in enumerate(row_sorted)
                           if c["fill"] >= row_mean + FILL_REL_MARGIN
                           and c["fill"] >= FILL_MIN_SIGNAL]

            # Decide which tier to use:
            # Always start with absolute hits; then also include any relative hits
            # that weren't already captured by absolute (catches secondary marks where
            # one fill is strong and a second is just above the relative threshold).
            abs_ranks = {r for r, _ in abs_filled}
            # Only count a relative-only hit as a genuine double-mark if it's
            # also close in fill to the absolute winner (≥ 70% of its fill).
            # This prevents lightly-border-noisy circles from triggering false
            # double-mark flags when the margin is lowered.
            primary_fill = max((c["fill"] for _, c in abs_filled), default=0.0)
            extra_rel = [
                (r, c) for r, c in rel_filled
                if r not in abs_ranks
                and (primary_fill == 0.0 or c["fill"] >= primary_fill * 0.70)
            ]
            if abs_filled:
                candidates = abs_filled + extra_rel
            elif len(rel_filled) > 1:
                # Multiple relative candidates — only keep all of them as
                # double-mark if the top-2 fills are very close (≥ 85% of top).
                # Otherwise pick only the single dominant one.
                rel_sorted = sorted(rel_filled, key=lambda x: x[1]["fill"], reverse=True)
                top_fill = rel_sorted[0][1]["fill"]
                if rel_sorted[1][1]["fill"] >= top_fill * 0.85:
                    candidates = rel_sorted  # genuinely similar → double-mark
                else:
                    candidates = [rel_sorted[0]]  # one clear winner
            else:
                candidates = rel_filled

            # ── Tier 3: dominant-max ──────────────────────────────────────────
            # If tiers 1+2 found nothing but one circle is clearly the most-filled
            # (≥ FILL_DOMINANT_R × the second-highest), select it.
            # Handles screen-photo images where backlight compression keeps
            # absolute fills low but the relative dominance is still clear.
            if not candidates and row_max >= FILL_MIN_SIGNAL:
                fills_desc = sorted(fills, reverse=True)
                ratio_ok = (len(fills_desc) == 1
                            or fills_desc[0] >= fills_desc[1] * FILL_DOMINANT_R)
                if ratio_ok:
                    max_rank = fills.index(row_max)
                    candidates = [(max_rank, row_sorted[max_rank])]

            def _rank_to_choice(rank):
                return RANK_TO_CHOICE.get(rank, "?")

            if not candidates:
                # Nothing confident — mark unanswered
                answers[q_str] = None
                details[q_str] = {
                    "choice": None, "note": "unanswered",
                    "n_choices": n_choices, "row_max_fill": round(row_max, 3),
                    "row_mean_fill": round(row_mean, 3),
                }

            elif len(candidates) == 1:
                rank, c = candidates[0]
                choice = _rank_to_choice(rank)
                tier   = "absolute" if abs_filled else "relative"
                answers[q_str] = choice
                details[q_str] = {
                    "choice": choice, "fill": c["fill"],
                    "rank": rank, "n_choices": n_choices,
                    "tier": tier, "row_mean_fill": round(row_mean, 3),
                }

            else:
                # Multiple candidates → pick the highest fill; flag double-mark
                best_rank, best_c = max(candidates, key=lambda x: x[1]["fill"])
                choice = _rank_to_choice(best_rank)
                tier   = "absolute" if abs_filled else "relative"
                answers[q_str] = choice
                details[q_str] = {
                    "choice": choice, "fill": best_c["fill"],
                    "rank": best_rank, "n_choices": n_choices,
                    "note": "double_mark", "tier": tier,
                    "all_filled": [_rank_to_choice(r) for r, _ in candidates],
                    "row_mean_fill": round(row_mean, 3),
                }

    return answers, details

# ── STEP 8: DEBUG VISUALISATION ───────────────────────────────────────────────

CHOICE_COLORS = {
    "A": (0, 220, 80),
    "B": (255, 165, 0),
    "C": (0, 200, 255),
    "D": (200, 0, 255),
    None: (120, 120, 120),
}

def draw_classified(warped: np.ndarray, cluster_grid: dict,
                    answers: dict, details: dict,
                    n_col_groups: int, rows_per_group: int,
                    debug_dir: pathlib.Path):
    """Draw classified circles with choice labels on the warped image."""
    vis_cls = warped.copy()
    vis_ans = warped.copy()

    for col_idx in range(n_col_groups):
        base_q = (n_col_groups - 1 - col_idx) * rows_per_group + 1
        rows = cluster_grid.get(col_idx, {})

        for row_idx in range(rows_per_group):
            q_num   = base_q + row_idx
            q_str   = str(q_num)
            row_circles = rows.get(row_idx, [])
            if not row_circles:
                continue

            row_sorted  = sorted(row_circles, key=lambda c: c["cx"], reverse=True)
            chosen      = answers.get(q_str)
            detail      = details.get(q_str, {})
            is_double   = detail.get("note") == "double_mark"
            # All choices that were detected as filled (for double-mark display)
            all_filled_choices = set(detail.get("all_filled", [chosen] if chosen else []))

            for rank, c in enumerate(row_sorted):
                choice     = RANK_TO_CHOICE.get(rank, "?")
                is_chosen  = (choice == chosen and chosen is not None)
                # Also highlight the other filled bubble(s) in a double-mark
                is_filled_other = is_double and choice in all_filled_choices

                # ── vis_cls: color by choice; thick border if above fill threshold ──
                col = CHOICE_COLORS.get(choice, (200, 200, 200))
                thick = 3 if c["filled"] else 1
                cv2.circle(vis_cls, (c["cx"], c["cy"]), c["r"], col, thick)
                cv2.putText(vis_cls, choice,
                            (c["cx"] - 5, c["cy"] + 4),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.25, col, 1)

                # ── vis_ans: answered sheet ────────────────────────────────────────
                if is_chosen or is_filled_other:
                    # Red outer ring for EVERY filled bubble when double-marked
                    # Green outer ring for clean single answers
                    ring_col = (0, 0, 255) if is_double else (0, 220, 0)
                    cv2.circle(vis_ans, (c["cx"], c["cy"]), c["r"] + 4, ring_col, 2)
                    cv2.circle(vis_ans, (c["cx"], c["cy"]), c["r"], (0, 0, 0), -1)
                    cv2.putText(vis_ans, choice,
                                (c["cx"] - 5, c["cy"] + 4),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.28,
                                (255, 255, 255), 1)
                else:
                    cv2.circle(vis_ans, (c["cx"], c["cy"]), c["r"],
                               (200, 200, 200), 1)

    _dbg(vis_cls, "08_circles_classified.jpg", debug_dir)
    _dbg(vis_ans, "09_answered.jpg", debug_dir)

# ── STEP 9: BUILD RESULT ──────────────────────────────────────────────────────

def build_result(image_path: str, qr: dict, answers: dict, details: dict,
                 n_questions: int, method: str, debug_dir: str) -> dict:
    unanswered    = [q for q in range(1, n_questions + 1)
                     if answers.get(str(q)) is None]
    double_marked = [q for q in range(1, n_questions + 1)
                     if details.get(str(q), {}).get("note") == "double_mark"]
    low_conf      = [q for q in range(1, n_questions + 1)
                     if details.get(str(q), {}).get("note") == "low_confidence"]

    return {
        "image":           image_path,
        "student_code":    qr.get("student_code", "UNKNOWN"),
        "exam_code":       qr.get("exam_code",    "UNKNOWN"),
        "qr_codes_raw":    qr.get("qr_raw", []),
        "align_method":    method,
        "answers":         {str(q): answers.get(str(q))
                            for q in range(1, n_questions + 1)},
        "answer_details":  details,
        "total_questions": n_questions,
        "answered":        n_questions - len(unanswered),
        "unanswered":      unanswered,
        "double_marked":   double_marked,
        "low_confidence":  low_conf,
        "valid":           len(unanswered) == 0 and len(double_marked) == 0,
        "debug_dir":       debug_dir,
    }

# ── MAIN PIPELINE ─────────────────────────────────────────────────────────────

def process(image_path: str, n_questions: int = 100) -> dict:
    stem      = pathlib.Path(image_path).stem
    debug_dir = pathlib.Path(f"detected-{stem}")
    debug_dir.mkdir(parents=True, exist_ok=True)
    print(f"\n=== OMR Detector: {image_path} ===")
    print(f"    debug dir: {debug_dir}/")

    # 1. Load
    print("[1] Loading image ...")
    img = load_image(image_path)
    _dbg(img, "00_original.jpg", debug_dir)
    print(f"    size: {img.shape[1]}x{img.shape[0]}")

    # 2. Warp
    print("[2] Aligning document ...")
    warped, method = align(img, debug_dir)

    # 3. Anchor verification (diagnostic only)
    print("[3] Verifying corner anchors ...")
    anchors = verify_anchors(warped, debug_dir)

    # 4. QR codes
    print("[4] Decoding QR codes ...")
    qr = decode_qr_codes(warped, debug_dir)

    # 5. Circle detection
    print("[5] Detecting answer circles ...")
    circles, _ = detect_answer_circles(warped, debug_dir, anchors=anchors)

    if len(circles) < 50:
        print(f"[WARN] Only {len(circles)} circles found. "
              "Tuning: try adjusting hough_param2 or fill_ratio_thr in CFG.")

    # 6. Cluster
    print("[6] Clustering circles into columns × rows ...")
    cluster_grid = cluster_circles(
        circles, CFG["n_col_groups"], CFG["rows_per_group"]
    )
    for cg, rows in cluster_grid.items():
        print(f"    col_group {cg}: {len(rows)} rows, "
              f"{sum(len(v) for v in rows.values())} circles")

    # 7. Extract answers
    print("[7] Extracting answers ...")
    answers, details = extract_answers(
        cluster_grid, CFG["n_col_groups"], CFG["rows_per_group"]
    )

    # 8. Debug visualisation
    print("[8] Saving debug visualisations ...")
    draw_classified(warped, cluster_grid, answers, details,
                    CFG["n_col_groups"], CFG["rows_per_group"], debug_dir)

    # 9. Build + save result
    print("[9] Building result ...")
    result = build_result(image_path, qr, answers, details,
                          n_questions, method, str(debug_dir))

    result_path = debug_dir / "result.json"
    with open(result_path, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

    print(f"\n[OK] Done.")
    print(f"     Answered:      {result['answered']} / {n_questions}")
    print(f"     Unanswered:    {result['unanswered'][:10]}{'...' if len(result['unanswered'])>10 else ''}")
    print(f"     Double-marked: {result['double_marked']}")
    print(f"     Low-conf:      {result['low_confidence'][:10]}{'...' if len(result['low_confidence'])>10 else ''}")
    print(f"     JSON:          {result_path}")
    return result

# ── ENTRY POINT ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="OMR Detector — Arabic Answer Sheet")
    ap.add_argument("image", help="Input answer sheet image (JPEG/PNG/etc.)")
    ap.add_argument("--questions", type=int, default=100,
                    help="Number of questions (default: 100)")
    ap.add_argument("--param2", type=int, default=None,
                    help="Override hough_param2 for circle sensitivity")
    ap.add_argument("--fill-thr", type=float, default=None,
                    help="Override fill_ratio_thr (0–1)")
    args = ap.parse_args()

    if args.param2:
        CFG["hough_param2"] = args.param2
    if args.fill_thr:
        CFG["fill_ratio_thr"] = args.fill_thr

    result = process(args.image, args.questions)
    # Print answer table
    print("\n--- Answers ---")
    for row in range(0, args.questions, 10):
        qs = range(row + 1, min(row + 11, args.questions + 1))
        print("  " + "  ".join(f"Q{q:3d}:{result['answers'].get(str(q)) or '-'}"
                                for q in qs))
